parameters:

services:
  # this makes public all the services defined in this file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  LaSalle\UrlShortener\JudithVilela\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Infrastructure\Ui\Cli\ShortenerCommand:
    arguments:
      - '@LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\UrlShortener\UrlShortener'
    tags:
      - { name: 'console.command', command: 'app:url-shortener' }
