parameters:

services:
  # this makes public all the services defined in this file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  LaSalle\UrlShortener\JudithVilela\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\GetShortenUrlsNumberPerCampaign\GetShortenUrlsNumberPerCampaign:
    arguments:
      - '@LaSalle\UrlShortener\JudithVilela\UrlShortened\Infrastructure\Persistence\Repository\MySQLShortenUrlsPerCampaignCounter'

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Infrastructure\Ui\Http\GetShortenUrlsNumberByCampaignController:
    arguments:
      - '@LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\GetShortenUrlsNumberPerCampaign\GetShortenUrlsNumberPerCampaign'

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\SaveUrlOnUrlWasShorten:
    tags:
      - { name: kernel.event_listener, event: 'url_shortened.url_was_shorten' }

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\UrlShortener\UrlShortener:
    arguments:
      - '@LaSalle\UrlShortener\JudithVilela\UrlShortened\Domain\Service\UrlShortener'

  LaSalle\UrlShortener\JudithVilela\UrlShortened\Infrastructure\Ui\Cli\ShortenerCommand:
    arguments:
      - '@LaSalle\UrlShortener\JudithVilela\UrlShortened\Application\UrlShortener\UrlShortener'
    tags:
      - { name: 'console.command', command: 'app:url-shortener' }
